### ISSUE TITLE
missing `easy-ai-index.owl`

### ISSUE THREAD

**Issue by cogan-shimizu** [kastle-lab/easy-ai#4]
Missing the index file to create the EASY-AI MODL

**Comment by threefinbdd** [comment]
1's annotations: https://github.com/kastle-lab/easy-ai/commit/536c867f71fa9196f81bf7f6019a4331ff733fe8
2's annotations: https://github.com/kastle-lab/easy-ai/commit/80c52577aaa5ff2b20131a7a7e7acb5826cf087b

also added index into commits.
